name: "API Verification"
run-name: "API Verification for ${{ github.ref_name }}"
on:
 workflow_run:
    workflows: [Ubuntu packaging]
    types:
      - completed
jobs:
  api_verification:
    runs-on: ubuntu-latest
    outputs:
      VERSION: ${{ steps.environment_step.outputs.VERSION }}
      FOO: ${{ steps.environment_step.outputs.FOO }}
    name: "Verify API for libkmnkbp0.so with FOO=${{ github.job.api_verification.outputs.FOO }} VERSION=${{github.job.api_verification.outputs.VERSION}}, ${{ vars.VERSION }}"

    steps:
    - name: Restore artifacts
      id: artifacts
      uses: actions/cache/restore@v4
      with:
        path: |
          artifacts
        key: artifacts-key-${{ github.event.workflow_run.id }}
        restore-keys: artifacts-key-

    - name: Read environment
      id: environment_step
      run: |
        echo "from context: GITHUB_RUN_ID=${{ github.event.workflow_run.id }}"
        ls -al artifacts/
        cat artifacts/env >> $GITHUB_ENV
        cat artifacts/env >> $GITHUB_OUTPUT
        echo "GITHUB_RUN_ID from README.md: $(cat artifacts/README.md)"
        echo "head_commit=${{ github.event.workflow_run.head_commit }}"
        echo "head_sha=${{ github.event.workflow_run.head_sha}}"
        echo "event=${{ github.event.workflow_run.event}}"
        echo "workflow.id=${{ github.event.workflow.id}}"
        echo "VERSION=47.11" >> $GITHUB_OUTPUT


    - name: Verify API
      run: |
        echo "Simulate verify API"
        echo "GITHUB_RUN_ID from README.md: $(cat artifacts/README.md)"
        echo "My GITHUB_RUN_ID: ${GITHUB_RUN_ID}, FOO=${FOO}, GIT_SHA=${GIT_SHA}"
        echo "with output: FOO=${{ steps.environment_step.outputs.FOO }} running on $(lsb_release -c -s)"
