name: "API Verification"
on:
 workflow_run:
    workflows: [Ubuntu packaging]
    types:
      - completed
jobs:
  api_verification:
    name: Verify API for libkmnkbp0.so
    runs-on: ubuntu-latest

    steps:
    - name: Restore artifacts
      id: artifacts
      uses: actions/cache/restore@v4
      with:
        path: |
          artifacts
        key: artifacts-key-${GITHUB_RUN_ID}
        restore-keys: artifacts-key-

    - name: Read environment
      run: |
        cat artifacts/env >> $GITHUB_ENV

    - name: Verify API
      run: |
        echo "Simulate verify API"
        echo "GITHUB_RUN_ID: $(cat artifacts/README.md)"
        echo "My GITHUB_RUN_ID: ${GITHUB_RUN_ID}, FOO=${FOO}, GIT_SHA=${GIT_SHA}"
