name: "Checkout bug #1201"
on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v6
      with:
        fetch-depth: 0
        clean: false

    - name: Restore artifacts
      run: |
        mkdir artifacts/
        echo "Hello world" > artifacts/hello

    - name: Verify
      run: |
        ls -al
        [ -d artifacts ] && ls -al artifacts/

  secondTest:
    runs-on: ubuntu-latest

    steps:
    - name: Do something
      run: |
        echo "Hello world!"
