name: 'Test failures'
run-name: '${{ github.actor }} is learning GitHub Actions'
on:
  workflow_dispatch:

jobs:
  build:
   name: Succeeding job
   runs-on: ubuntu-latest
   steps:
    - name: Build
      run: exit 0

  job2:
    name: Failing job
    needs: build
    runs-on: ubuntu-latest
    steps:
     - name: Foo
       run: exit 1

  job3:
    name: Also succeeds
    needs: build
    runs-on: ubuntu-latest
    steps:
     - name: Build
       run: exit 0
