name: 'Test failures'
run-name: '${{ github.actor }} is learning GitHub Actions'
on:
  workflow_dispatch:

jobs:
  build:
   name: Succeeding job
   runs-on: ubuntu-latest
   steps:
    - name: Build
      run: exit 0
    - name: Failing
      continue-on-error: true
      run: exit 1
    - name: Output
      run: echo "Hello world!"

  job2:
    name: Failing job
    needs: build
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
     - name: Foo
       run: exit 1

  job_matrix:
    name: A failing matrix job
    needs: build
    continue-on-error: true
    strategy:
      fail-fast: true
      matrix:
        dist: [noble]
    runs-on: ubuntu-latest
    steps:
     - name: Hello
       run: echo "Hello ${{ matrix.dist }} world!"

     - name: Now fail
       run: exit 1

  job3:
    name: Also succeeds
    needs: build
    runs-on: ubuntu-latest
    steps:
     - name: Build
       run: exit 0
